site_name: "Architecture Documentation"
theme:
  name: "material"

plugins:
  - plantuml:
      puml_url: "http://plantuml:8080"
      theme:
        enabled: false
  - search:
  - macros:
  - mermaid2:
      version: 11.12.0
  - build_plantuml:
      render: 'server'
      server: 'http://plantuml:8080'
      output_format: 'svg' # or "png"
      allow_multiple_roots: false # in case your codebase contains more locations for diagrams (all ending in diagram_root)
      diagram_root: 'docs/diagrams' # should reside under docs_dir
      output_folder: 'generated'
      input_folder: 'src'
      input_extensions: 'puml' # comma separated list of extensions to parse, by default every file is parsed
nav:
  - Home ({{ git_version }}): index.md
  - Architecture: architecture.md
  - ADR: adr.md
  - Diagrams:
      - Generic Architecture Diagrams: diagrams/architecture.md
      - C4/PlantUML Example: simulationQueueC4.md
      - C4/Mermaid Example : simulationQueueC4Mermaid.md
      - C4/Mermaid experimental Example: simulationQueueC4MermaidX.md
dev_addr: 0.0.0.0:8000  # need to bind to all interfaces in devcontainer to enable access from host
markdown_extensions:
  - pymdownx.snippets