version: '3.8'

services:
  mkdocs:
    build:
      dockerfile: .devcontainer/mkdocs.dockerfile
      context: ..
    volumes:
      - ..:/workspace
    ports:
      - "8000:8000"
    environment:
      - PLANTUML_SERVER=http://plantuml:8080
    stdin_open: true
    tty: true

  plantuml:
    image: plantuml/plantuml-server:jetty
    ports:
      - "8080:8080"