name: Release and Deploy Docs

on:
  push:
    branches: ["**"]

permissions:
  pages: write        # For GitHub Pages deployment
  id-token: write        # For GitHub Pages deployment
  contents: write          # For committing version + changelog
  issues: write            # For commenting on issues
  pull-requests: write     # For commenting on PRs

jobs:
  release_and_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed so semantic-release sees tags

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci  # Or your environment setup

      - name: Run semantic-release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      # Capture new version produced by semantic-release
      # Assumes your semantic-release plugin writes the version to a file or env
      - name: Get released version
        run: echo "VERSION=$(git describe --tags --always)" >> $GITHUB_ENV

      - name: Build MkDocs site inside Docker using version
        env:
          PROJECT_VERSION: ${{ env.VERSION }}
        run: |
          mkdir -p docs/diagrams/generated
          mkdir -p site
          chmod o+rw docs/diagrams/generated site
          make build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./site
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          force_orphan: true
