name: Publish MkDocs to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Export env file for docker-compose
        run: |
          # Export a minimal set of env vars for the container. Add secrets if your deploy needs them.
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" > .env
          echo "CI=true" >> .env
          # Export runner UID/GID so containers can run as the host user and write bind-mounted files
          echo "LOCAL_UID=$(id -u)" >> .env
          echo "LOCAL_GID=$(id -g)" >> .env

      - name: Deploy site (make deploy)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true
          LOCAL_UID: ${{ env.LOCAL_UID }}
          LOCAL_GID: ${{ env.LOCAL_GID }}
        run: |
          mkdir -p docs/diagrams/generated
          chmod o+rw docs/diagrams/generated
          make deploy
